### ISSUE TITLE
Getting error when setting retainUncompressedFiles to false

### ISSUE THREAD

**Issue by giovanniPepi** [jnsjknn/compress-create-react-app#11]
There seems to be a error after compressing files when `retainUncompressedFiles` is set to false. Without this option, the br compression runs as usual and the only difference is that it stores original webp files

```
[compress-create-react-app]:
Compressing build files...
    
node:fs:1538
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, stat '/home/hostname/02repos/weatherts/build/index.html'
    at Object.statSync (node:fs:1538:3)
    at /home/hostname/02repos/weatherts/node_modules/compress-create-react-app/src/getCombinedSize.js:6:21
    at Array.forEach (<anonymous>)
    at getCombinedSize (/home/hostname/02repos/weatherts/node_modules/compress-create-react-app/src/getCombinedSize.js:5:16)
    at printResult (/home/hostname/02repos/weatherts/node_modules/compress-create-react-app/src/printResult.js:6:28)
    at /home/hostname/02repos/weatherts/node_modules/compress-create-react-app/src/index.js:21:5 {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/home/hostname/02repos/weatherts/build/index.html'
}
```

compress-cra.json: 

```
{
  "algorithms": ["br"],
  "filetypes": [
    ".html",
    ".js",
    ".css",
    ".svg",
    ".png",
    ".jpg",
    ".webp",
    ".mp3",
    ".wav",
    ".tff",
    ".woff2",
    ".map"
  ],
  "directory": "/build",
  "retainUncompressedFiles": false
}
```

npm 8.19.2
node v16.14.2

thanks

**Comment by jnsjknn** [comment]
Thanks for a good bug report @giovanniPepi! I was easily able to duplicate the error and I'll look into it as soon as possible.

**Comment by dan96ct** [comment]
Hi, this would be a simple solution:

In index.js, change this:
```
algorithms.forEach(async (algorithm) => {
    await startCompressingAll(filesToCompress, algorithm);
    printResult(buildDir, algorithm, filesToCompress);
  });
```

For this:
```
for (const algorithm of algorithms) {
    await startCompressingAll(filesToCompress, algorithm);
    printResult(buildDir, algorithm, filesToCompress);
 }
```
When forEach execute a async function not waits for finish it, work for me
